import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@src/components/session-wrapper";
import SessionAuthProvider from "@src/context/session-auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionAuthProvider>
          {children}
        </SessionAuthProvider>
      </body>
    </html>
  );
}
